version: "3.9"

services:

  todoapp:
    build: ./app
    restart: always
    ports:
      - "80:80"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      ZIPKIN_SERVER_URL: http://zipkin:9411
    depends_on:
      - postgres
      - zipkin

  postgres:
    image: postgres:14.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  prometheus:
    image: prom/prometheus:v2.36.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:8.5.6
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  zipkin:
    image: openzipkin/zipkin:2.23.16
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: cassandra3
      CASSANDRA_CONTACT_POINTS: zipkin-cassandra
    depends_on:
      - zipkin-cassandra

  zipkin-cassandra:
    image: cassandra:3.11.13
    volumes:
      - zipkin-data:/var/lib/cassandra

volumes:
  postgres-data:
  prometheus-data:
  zipkin-data: