version: "3.9"

services:

  todoapp:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: "postgres:14.3"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres