###
GET http://localhost/todo

###
POST http://localhost/todo
Content-Type: application/json

{
  "todo": {
    "text": "Купить масло"
  }
}

###
PUT http://localhost/todo/1
Content-Type: application/json

{
  "todo": {
    "done": true
  }
}

###
DELETE http://localhost/todo/5